Description: This YAML file is used to configure database resources for the application, including RDS instances and Secrets Manager entries for storing database credentials securely.
Resources:
  MyDatabase:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: 'Delete'
    Properties:
      DBInstanceIdentifier: countries-1
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername: admin
      ManageMasterUserPassword: True
      VPCSecurityGroups:
        - !Ref MyDatabaseSecurityGroup
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      DeletionPolicy: False

  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for the database
      SubnetIds:
        - !Ref FirstPrivateSubnet
        - !Ref SecondPrivateSubnet
        - !Ref ThirdPrivateSubnet
        - !Ref FourthPrivateSubnet

  MyDatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the RDS instance
      VpcId: !Ref MainVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306 # MySQL port
          ToPort: 3306
          CidrIp: 10.0.0.0/16 # Restrict access to the VPC CIDR range
